#!/usr/bin/env -S npx tsx
/**
 * Generates circuits/ecdsa/g_table.circom containing:
 *   SECP256K1_G_TABLE(n, k) → powers[32][256][2][4]
 *
 * Table structure:
 *   powers[stride][selector][coord][limb]
 *   = (selector * 2^(8*stride)) * G   for selector ∈ [1, 255]
 *   = 0 (placeholder)                  for selector == 0
 *
 * With stride=8, there are 32 strides (256/8) and 256 selector values.
 * Total: 32 * 255 * 2 * 4 = 65,280 non-zero values.
 */

import { secp256k1 } from "@noble/curves/secp256k1.js";
import { writeFileSync } from "fs";
import { join } from "path";

const Point = secp256k1.Point;
const STRIDE = 8;
const NUM_STRIDES = 32; // 256 / 8
const SELECTOR_COUNT = 1 << STRIDE; // 256
const N = 64;
const K = 4;

function toLimbs64(val: bigint): bigint[] {
    const mask = (1n << 64n) - 1n;
    return Array.from({ length: K }, (_, i) => (val >> (BigInt(i) * 64n)) & mask);
}

console.log("Computing G table for secp256k1 (stride=8, n=64, k=4)...");

// Precompute stride bases: G, 2^8*G, 2^16*G, ..., 2^248*G
const strideBases: Array<InstanceType<typeof Point>> = [];
let base = Point.BASE;
for (let s = 0; s < NUM_STRIDES; s++) {
    strideBases.push(base);
    // Advance base by 2^8 (double 8 times)
    for (let d = 0; d < STRIDE; d++) {
        base = base.double();
    }
}

let lines: string[] = [];
lines.push("pragma circom 2.2.2;");
lines.push("");
lines.push("// ═══════════════════════════════════════════════════");
lines.push("// Precomputed G table for stride-8 windowed scalar multiplication.");
lines.push("// powers[stride][selector][coord][limb] = (selector * 2^(8*stride)) * G");
lines.push("// Generated by scripts/gen_g_table.ts — DO NOT EDIT.");
lines.push("// ═══════════════════════════════════════════════════");
lines.push("");
lines.push("function SECP256K1_G_TABLE(n, k) {");
lines.push(`    assert(n == ${N} && k == ${K});`);
lines.push(`    var powers[${NUM_STRIDES}][${SELECTOR_COUNT}][2][${K}];`);

let pointCount = 0;
for (let s = 0; s < NUM_STRIDES; s++) {
    // selector=0: point at infinity placeholder (all zeros)
    for (let c = 0; c < 2; c++) {
        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][0][${c}][${l}] = 0;`);
        }
    }

    // selector=1..255: j * strideBases[s]
    let current = strideBases[s]; // 1 * stride base
    for (let j = 1; j < SELECTOR_COUNT; j++) {
        const aff = current.toAffine();
        const xLimbs = toLimbs64(aff.x);
        const yLimbs = toLimbs64(aff.y);

        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][${j}][0][${l}] = ${xLimbs[l]};`);
        }
        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][${j}][1][${l}] = ${yLimbs[l]};`);
        }

        if (j < SELECTOR_COUNT - 1) {
            current = current.add(strideBases[s]);
        }
        pointCount++;
    }

    if ((s + 1) % 4 === 0) {
        console.log(`  Stride ${s + 1}/${NUM_STRIDES} done (${pointCount} points computed)`);
    }
}

lines.push("");
lines.push("    return powers;");
lines.push("}");
lines.push("");

const outPath = join(import.meta.dirname!, "..", "circuits", "ecdsa", "g_table.circom");
writeFileSync(outPath, lines.join("\n"));

console.log(`\nWrote ${outPath}`);
console.log(`  ${pointCount} points, ${lines.length} lines`);
