#!/usr/bin/env -S npx tsx
/**
 * Generates circuits/ecdsa/g_table.circom containing:
 *   SECP256K1_G_TABLE(n, k) → powers[NUM_STRIDES][SELECTOR_COUNT][2][K]
 *
 * Table structure:
 *   powers[stride][selector][coord][limb]
 *   = (selector * 2^(STRIDE*stride)) * G   for selector ∈ [1, SELECTOR_COUNT-1]
 *   = 0 (placeholder)                       for selector == 0
 *
 * With stride=6, there are 43 strides (ceil(256/6)) and 64 selector values.
 * Total: 43 * 63 * 2 * 8 = 43,344 non-zero values.
 */

import { secp256k1 } from "@noble/curves/secp256k1.js";
import { writeFileSync } from "fs";
import { join } from "path";

const Point = secp256k1.Point;
const STRIDE = 6;
const NUM_STRIDES = Math.ceil(256 / STRIDE); // 43
const SELECTOR_COUNT = 1 << STRIDE; // 64
const N = 32;
const K = 8;

function toLimbs32(val: bigint): bigint[] {
    const mask = (1n << 32n) - 1n;
    return Array.from({ length: K }, (_, i) => (val >> (BigInt(i) * 32n)) & mask);
}

console.log(`Computing G table for secp256k1 (stride=${STRIDE}, n=${N}, k=${K})...`);

// Precompute stride bases: G, 2^STRIDE*G, 2^(2*STRIDE)*G, ...
const strideBases: Array<InstanceType<typeof Point>> = [];
let base = Point.BASE;
for (let s = 0; s < NUM_STRIDES; s++) {
    strideBases.push(base);
    // Advance base by 2^STRIDE (double STRIDE times)
    for (let d = 0; d < STRIDE; d++) {
        base = base.double();
    }
}

let lines: string[] = [];
lines.push("pragma circom 2.2.2;");
lines.push("");
lines.push("// ═══════════════════════════════════════════════════");
lines.push(`// Precomputed G table for stride-${STRIDE} windowed scalar multiplication.`);
lines.push(`// powers[stride][selector][coord][limb] = (selector * 2^(${STRIDE}*stride)) * G`);
lines.push("// Generated by scripts/gen_g_table.ts — DO NOT EDIT.");
lines.push("// ═══════════════════════════════════════════════════");
lines.push("");
lines.push("function SECP256K1_G_TABLE(n, k) {");
lines.push(`    assert(n == ${N} && k == ${K});`);
lines.push(`    var powers[${NUM_STRIDES}][${SELECTOR_COUNT}][2][${K}];`);

let pointCount = 0;
for (let s = 0; s < NUM_STRIDES; s++) {
    // selector=0: point at infinity placeholder (all zeros)
    for (let c = 0; c < 2; c++) {
        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][0][${c}][${l}] = 0;`);
        }
    }

    // selector=1..SELECTOR_COUNT-1: j * strideBases[s]
    let current = strideBases[s]; // 1 * stride base
    for (let j = 1; j < SELECTOR_COUNT; j++) {
        const aff = current.toAffine();
        const xLimbs = toLimbs32(aff.x);
        const yLimbs = toLimbs32(aff.y);

        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][${j}][0][${l}] = ${xLimbs[l]};`);
        }
        for (let l = 0; l < K; l++) {
            lines.push(`    powers[${s}][${j}][1][${l}] = ${yLimbs[l]};`);
        }

        if (j < SELECTOR_COUNT - 1) {
            current = current.add(strideBases[s]);
        }
        pointCount++;
    }

    if ((s + 1) % 5 === 0) {
        console.log(`  Stride ${s + 1}/${NUM_STRIDES} done (${pointCount} points computed)`);
    }
}

lines.push("");
lines.push("    return powers;");
lines.push("}");
lines.push("");

const outPath = join(import.meta.dirname!, "..", "circuits", "ecdsa", "g_table.circom");
writeFileSync(outPath, lines.join("\n"));

console.log(`\nWrote ${outPath}`);
console.log(`  ${pointCount} points, ${lines.length} lines`);
